var gulp = require('gulp'),
	uglify = require('gulp-uglify'),
	sass = require('gulp-sass'),
	plumber = require('gulp-plumber'),
	imagemin = require('gulp-imagemin'),
	autoprefixer = require('gulp-autoprefixer'),
	concat = require('gulp-concat'),
	sourcemaps = require('gulp-sourcemaps'),
	rename = require("gulp-rename"),
	cleanCSS = require('gulp-clean-css'), // Ex minify-css
	rev = require('gulp-rev'),
	del = require('del'),
	browserSync = require('browser-sync').create(); 

var paths = {
	// Source
	srcSass: 'resources/sass/*.sass',
	srcJs: 'resources/js/*.js',
	srcImg: 'resources/img/*',

	// Destination
	destCss: 'static/css',
	destJs: 'static/js',
	destImg: 'static/img',
}
var expandedFiles = {
	css : 'styles.css',
	js : 'all.js',
};
var compressedFiles = {
	css : 'styles.min.css',
	js : 'all.min.js',
};

// Scripts task
// Uglifies
gulp.task('preProcess:scripts', function () {
	// Uncompressed all JS file
	return gulp.src(paths.srcJs)
	.pipe(sourcemaps.init())
	.pipe(concat(expandedFiles.js))
	.pipe(sourcemaps.write('maps'))		
	.pipe(gulp.dest(paths.destJs))
	.on('error', console.error.bind(console));

});

gulp.task('scripts', ['preProcess:scripts'], function () {	
	// Compressed all JS file
	gulp.src(paths.destJs + '/' + expandedFiles.js)	
	.pipe(sourcemaps.init({loadMaps:true}))
	.pipe(rename(compressedFiles.js))		
	.pipe(uglify())	
	.pipe(rev())	
	.pipe(sourcemaps.write('maps'))		
	.pipe(gulp.dest(paths.destJs))
	.pipe(rev.manifest())			
	.pipe(gulp.dest(paths.destJs))
	.on('error', console.error.bind(console));
});

// preProcess:styles Task
// Convert sass to css and then generates an uncompressed css file
gulp.task('preProcess:styles', function () 
{
	return gulp.src(paths.srcSass)
	.pipe(sourcemaps.init())
	.pipe(sass({
		outputStyle: 'expanded'
	}).on('error', console.error.bind(console)))
	.pipe(concat(expandedFiles.css))	
	.pipe(autoprefixer('last 2 versions','> 1%'))	
	.pipe(sourcemaps.write('maps'))	
	.pipe(gulp.dest(paths.destCss));
	console.log('Styles processed');
	
});

// styles Task
// minifies the uncompressed file generated by preProcess:styles task
// and then generates a hashed name to deal with browser cache
gulp.task('styles', ['preProcess:styles'], function () 
{	
	gulp.src(paths.destCss + '/' + expandedFiles.css)
	.pipe(sourcemaps.init({loadMaps:true}))
	.pipe(cleanCSS())
	.pipe(rename({
		basename: "styles",
		suffix: ".min",
		extname: ".css"
	}))		
	.pipe(rev())		
	.pipe(sourcemaps.write('maps'))		
	.pipe(gulp.dest(paths.destCss))
	.pipe(rev.manifest())			
	.pipe(gulp.dest(paths.destCss));
});

// Image Task
// Compress all images
gulp.task('images', function () {
	gulp.src(paths.srcImg)
	.pipe(imagemin())
	.pipe(gulp.dest(paths.destImg));
});
gulp.task('clean', function () {
	return  del([
		'static/*'
	]);
});
// Watch task
// watches js and css and rebuild everytime files are saved
gulp.task('watch', function () {
	gulp.watch([paths.srcJs], ['scripts', browserSync.reload]);
	gulp.watch([paths.srcSass], ['styles', browserSync.reload]);
	gulp.watch(['./*.html'], browserSync.reload);
});

gulp.task('default', ['clean'], function(){
	gulp.start(['scripts', 'styles', /*'images',*/ 'watch', 'browser-sync']);
});

gulp.task('browser-sync', function(){
	browserSync.init({
		proxy: "snippets.dev/gulp-project",
	});
})